---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/doctors/{doctor_id}/appointments":
    parameters:
    - name: doctor_id
      in: path
      type: string
      description: doctor_id
      required: true
    get:
      summary: list appointments
      responses:
        '200':
          description: successful
    post:
      summary: create appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: appointment
        in: body
        schema:
          type: object
          properties:
            date_of_appointment:
              type: string
            time_of_appointment:
              type: string
            description:
              type: string
            user_id:
              type: string
            doctor_id:
              type: string
          required:
          - date_of_appointment
          - time_of_appointment
          - description
          - user_id
          - doctor_id
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{doctor_id}/appointments/{id}":
    parameters:
    - name: doctor_id
      in: path
      type: string
      description: doctor_id
      required: true
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show appointment
      responses:
        '200':
          description: successful
    patch:
      summary: update appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: appointment
        in: body
        schema:
          type: object
          properties:
            date_of_appointment:
              type: string
            time_of_appointment:
              type: string
            description:
              type: string
            user_id:
              type: string
            doctor_id:
              type: string
          required:
          - date_of_appointment
          - time_of_appointment
          - description
          - user_id
          - doctor_id
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    put:
      summary: update appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: appointment
        in: body
        schema:
          type: object
          properties:
            date_of_appointment:
              type: string
            time_of_appointment:
              type: string
            description:
              type: string
            user_id:
              type: string
            doctor_id:
              type: string
          required:
          - date_of_appointment
          - time_of_appointment
          - description
          - user_id
          - doctor_id
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    delete:
      summary: delete appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
    post:
      summary: create doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: doctor
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            specialization:
              type: string
            picture:
              type: string
          required:
          - name
          - specialization
          - picture
      consumes:
      - application/json
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    patch:
      summary: update doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: doctor
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            specialization:
              type: string
            picture:
              type: string
          required:
          - name
          - specialization
          - picture
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    put:
      summary: update doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: doctor
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            specialization:
              type: string
            picture:
              type: string
          required:
          - name
          - specialization
          - picture
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - password
          - password_confirmation
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - password
          - password_confirmation
      responses:
        '200':
          description: successful
    put:
      summary: update user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - password
          - password_confirmation
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
  "/api/v1/auth/signup":
    post:
      summary: create user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - password
          - password_confirmation
      responses:
        '200':
          description: successful
  "/auth/login":
    post:
      summary: login user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: successful
  "/api/v1/patient/appointments":
    get:
      summary: users appointments
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
